version: '3'

services:
  jobbackend-service:
    build:
      context: .
      dockerfile: ./job.dockerfile
    restart: always
    ports: 
      - "80:8080"
    deploy:
      mode: replicated
      replicas: 1
    environment:
      DSN: postgres://postgres_1_yvg0_user:LOgPvWQEEDLpDbx2HbKIsHPMbjE7BBjY@dpg-cnk40n821fec73e77ing-a.oregon-postgres.render.com/postgres_1_yvg0
      Local: postgresql://postgres:philippians@localhost:5432/postgres?sslmode=disable
      SECRET_KEY: HMACSHA1
